global using global::System;
global using global::System.Collections.Generic;
global using global::System.Collections.Immutable;
global using global::System.Diagnostics;
global using global::System.Diagnostics.CodeAnalysis;
global using global::System.Linq;
global using global::System.Text;
global using global::System.Threading.Tasks;
global using global::Brimborium.PolyData;
